{{- if .Values.gitlab.runner.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devsecops-pipeline.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops-pipeline.labels" . | nindent 4 }}
data:
  config.toml: |
    concurrent = {{ .Values.gitlab.runner.concurrent }}
    check_interval = {{ .Values.gitlab.runner.checkInterval }}
    shutdown_timeout = 30

    [session_server]
      session_timeout = 1800

    [[runners]]
      url = {{ .Values.gitlab.runner.gitlabUrl | quote }}
      executor = "kubernetes"
      environment = ["FF_USE_ADVANCED_POD_SPEC_CONFIGURATION=true"]

      [runners.kubernetes]
        namespace = {{ .Release.Namespace | quote }}
        image = "alpine:3.19"
        pull_policy = "always"
        service_account = {{ include "devsecops-pipeline.serviceAccountName" . | quote }}
        privileged = false
        allow_privilege_escalation = false

        cpu_request = "100m"
        cpu_limit = "2000m"
        memory_request = "128Mi"
        memory_limit = "2Gi"

        [runners.kubernetes.pod_labels]
          "app" = "gitlab-runner-job"
          "managed-by" = "gitlab-runner"
          "app.kubernetes.io/instance" = {{ .Release.Name | quote }}

        [runners.kubernetes.pod_security_context]
          run_as_non_root = true
          run_as_user = 1000
          fs_group = 1000

        [[runners.kubernetes.volumes.empty_dir]]
          name = "tmp"
          mount_path = "/tmp"
          medium = "Memory"

        [[runners.kubernetes.volumes.empty_dir]]
          name = "home"
          mount_path = "/home/gitlab-runner"
{{- end }}
