{{- if and .Values.gitlab.runner.enabled (not .Values.gitlab.runner.existingSecret) }}
{{- if .Values.gitlab.runner.runnerToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devsecops-pipeline.fullname" . }}-runner-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devsecops-pipeline.labels" . | nindent 4 }}
  annotations:
    # keep: Retain secret on helm uninstall to prevent runner re-registration.
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  # runner-token: GitLab runner registration token.
  # Referenced by the runner Deployment as an environment variable.
  runner-token: {{ .Values.gitlab.runner.runnerToken | quote }}
{{- end }}
{{- end }}
