{{- if and .Values.grafana.enabled (not .Values.grafana.admin) }}
{{- if .Values.grafana.adminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "observability-stack.fullname" . }}-grafana-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability-stack.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  # admin-user: Grafana admin username.
  admin-user: admin
  # admin-password: Grafana admin password. Populated from grafana.adminPassword value.
  admin-password: {{ .Values.grafana.adminPassword | quote }}
{{- end }}
{{- end }}
