{{- if and .Values.postgresql.enabled (not .Values.postgresql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql-ha.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgresql-ha.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  postgres-password: {{ required "postgresql.auth.postgresPassword is required" .Values.postgresql.auth.postgresPassword | quote }}
  password: {{ .Values.postgresql.auth.password | default "" | quote }}
  replication-password: {{ randAlphaNum 32 | quote }}
{{- end }}
